## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per enviornment.
authorizations: &AUTHORIZATIONS
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: postsAdmin
## Environment
production:
  host: localhost
  port: 389
  attribute: uid
  base: OU=users,DC=example,DC=net
  ssl: false
  # <<: *AUTHORIZATION